default["phpapp"]["path"] = "/var/www/html/phpapp"
default['phpapp']['server_name'] = "phpapp"
default['phpapp']['user_name'] = "phpapp"
default['phpapp']['database'] = "phpapp"
default['phpapp']['db_username'] = "phpapp"
